# config.yaml - User configuration for Intv_App
#
# This file contains all user-editable settings for the CLI and LLM/RAG system.
# Place this file in the config/ directory. Edit as needed to set defaults for your environment.
#
# For more information, see the README.md or project documentation.

# LLM API base URL (KoboldCpp, OpenAI)
llm_api_base: "http://localhost"

# LLM API key (if required)
# llm_api_key: "your-api-key-here"

# LLM API port (KoboldCpp default: 5001)
llm_api_port: 5001

# LLM provider: koboldcpp, openai
llm_provider: "koboldcpp"  # Options: koboldcpp, openai

# Model name or ID (KoboldCpp default shown)
model: "hf.co/unsloth/Phi-4-reasoning-plus-GGUF:Q5_K_M"

# Use external RAG service (true/false)
external_rag: false

# Purge variables from the database on run (true/false)
purge_variables: false

#
# Multi-user login info is now stored in config/users.yaml.
# To enable multi-user support, edit config/users.yaml and add users as needed.
# The default_user above is ignored if users.yaml exists and is non-empty.
#
# You can remove the default_user block above if you want to require users.yaml for all logins.
#
# Add more global settings as needed below.
# For example:
# default_language: "en"
# enable_diarization: true
# enable_vad: true
# transcription_output_format: "json"
# rag_backend: "local"  # or "cloud"
