# config.yaml - User configuration for python-cli-app
#
# This file contains all user-editable settings for the CLI and LLM/RAG system.
# Place this file in the config/ directory. Edit as needed to set defaults for your environment.
#
# For more information, see the README.md or project documentation.

# LLM API base URL (Ollama, OpenAI, etc.)
llm_api_base: "http://localhost"

# LLM API key (if required)
# llm_api_key: "your-api-key-here"

# LLM API port (Ollama default: 11434)
llm_api_port: 11434

# LLM provider: openai, ollama, koboldcpp, etc.
llm_provider: "ollama"

# Model name or ID (Ollama default shown)
model: "hf.co/unsloth/Phi-4-reasoning-plus-GGUF:Q5_K_M"

# Use external RAG service (true/false)
external_rag: false

# Purge variables from the database on run (true/false)
purge_variables: false

# Default user for web GUI login
# If unchanged, the default is: username: admin, password: password123
# Set these to secure values in production!
default_user:
  username: "admin"
  password: "password123"
  role: "admin"
  name: "User"
# You can add more users below (for future multi-user support)
# users:
#   - username: "user1"
#     password: "changeme"
#     role: "user"
#     name: "user"

# Add more global settings as needed below.
# For example:
# default_language: "en"
# enable_diarization: true
# enable_vad: true
# transcription_output_format: "json"
# rag_backend: "local"  # or "cloud"
